### ISSUE TITLE
Error: Host not found in upstream "radar-integration" in /etc/nginx/optional-services.conf:3

### ISSUE THREAD

**Issue by kafe09** [RADAR-base/RADAR-Docker#233] opened 2020-12-03 12:35 UTC
Dear all, unfortunately this error appears when trying 
**Step 12: Verify the status of all the docker services.**
1 | docker ps -a
All of the services should eventually become “healthy” except radarbase/kafka-init, which should state Exit 0.
BUT: here the error "**Host not found in upstream "radar-integration" in /etc/nginx/optional-services.conf:3".**

Can someone help us with this issue? 

Looking forward hearing from you.

**Comment by yatharthranjan** [comment] 2020-12-03 12:38
radarbase/kafka-init exited 0 is expected since it is a run once service and stops after completing. 

For host not found, please refer to #230. Also please search the issues first, there is a high probability there is already an issue reported for your problem.

**Comment by kafe09** [comment] 2020-12-03 12:39
Thank you so much!

**Comment by nivemaham** [comment] 2020-12-04 13:21
Duplicate of #230

**Closed by nivemaham** 2020-12-04 13:21 UTC
